version: '2.1'

services:
  middleware:
    container_name: fswalker
    build:
      context: .
      dockerfile: Dockerfile
    command:
      npm start
    volumes:
      - ./:/var/data:ro
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - .env
